### PR TITLE
Restore symfony console 2.3 support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Was there a reason this was removed?

### CODE REVIEW

**Comment by bobthecow** [comment]
I'm not sure, I probably just missed it when merging the PHP 5.4+ PR.

Tested and it works great, so let's add it back!

**Comment by GrahamCampbell** [comment]
👍

**Comment by bobthecow** [comment]
In keeping with our long, rich tradition of releasing `v0.x.1` as fast as possible after `v0.x.0`, this has gone out as `v0.9.1`. Thanks for catching it 😄

**Comment by GrahamCampbell** [comment]
🚢

**Comment by GrahamCampbell** [comment]
So is php 5.4, and 5.5, and symfony 2.4, 2.5, and 2.6 was ages ago. Why does that matter? It's not the job of this package to force people not to use them. If it works fine, there's no real case for not supporting them.

**Comment by GrahamCampbell** [comment]
> Seriously, update if you can.

If people can, then they will. Nobody's saying people have to use 2.3, but if they need too, then can. ;)

**Comment by GrahamCampbell** [comment]
btw https://symfony.com/roadmap?version=2.4#checker :P

**Comment by Taluu** [comment]
Didn't even mention 2.4, 2.5 and 2.6 because 2.3 was a lts that was finished a year ago. Yes, it is indeed a library to not push people to upgrade. But it's not a library's job either to support unmaintained libraries.

**Pull request merged**
