### PR TITLE
make doc command support complete

### PR DESCRIPTION
**Pull request by lvht**

### CODE REVIEW

**Comment by lvht** [comment]
Hi @bobthecow , this patch does not work for `doc Composer\Autoload\ClassLoader::<tab>`. Could you offer any advice?

**Comment by bobthecow** [comment]
Why should `doc` be special? What about `ls` and `show`? :)

**Comment by lvht** [comment]
@bobthecow support ls and show

**Comment by lvht** [comment]
ping @bobthecow

**Comment by bobthecow** [comment]
Sorry about the delay. I finally tracked down and fixed the namespaced class property and method completion! (It was an existing bug; see 1f9bc08)

This looks good to me.

**Comment by bobthecow** [comment]
Thanks for your contribution. This will go out in the next stable release.

**Pull request merged**
