### PR TITLE
proposal for #ticket_154 

### PR DESCRIPTION
**Pull request by Markcial**
quirky fix with a cancellable forking loop that aborts long running operations with kill signal without exiting from the psysh shell, can be set as a parameter

### CODE REVIEW

**Comment by Markcial** [comment]
This PR might seem unrelated https://github.com/bobthecow/psysh/pull/138 but it has a loop refactor proposal that could involve this forking loop, linked here just as a side not for any visitor in this thread.

**Comment by bobthecow** [comment]
I haven't taken any time to dig into why, but it's definitely not working right just yet:

screen shot 2015-02-19 at 11 16 41 pm

**Comment by Markcial** [comment]
Ok, thanks for the hint, don't waste your time on that. I will check for that later and write a test covering the case.

**Comment by bobthecow** [comment]
Do you mind re-opening this pull request against develop?

**Comment by Markcial** [comment]
done, i will close this PR then

**Pull request closed without merging**
