### PR TITLE
Develop is now 0.10

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I think?

### CODE REVIEW

**Comment by bobthecow** [comment]
There aren't any backwards compatibility breaks in `develop` so far, so if I were to cut a release right now it'd be 0.9.4.

**Comment by bobthecow** [comment]
Yeah, the isolated version would likely be v0.10.

**Comment by GrahamCampbell** [comment]
> There aren't any backwards compatibility breaks in develop so far, so if I were to cut a release right now it'd be 0.9.4.

Doesn't semver dictate new features require a minor version bump?

**Comment by bobthecow** [comment]
>Doesn't semver dictate new features require a minor version bump?

Not for v0.x.

**Comment by bobthecow** [comment]
The real answer is that I should release a v1.0 some day and then Server will do what you expect ;)

Closing for now.

**Pull request closed without merging**
