### PR TITLE
Fixed up the use statement pass class

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests seem to be passing. :)

**Comment by bobthecow** [comment]
:+1:

**Comment by bobthecow** [comment]
Since this is broken IRL right now, I'd like to get it shipped. Is there anything else that should go in the point release that isn't already in develop?

**Comment by GrahamCampbell** [comment]
That php7 thing.

**Comment by GrahamCampbell** [comment]
I'm rebasing it now.

**Pull request merged**
