### PR TITLE
Critial fix to php-parser version constraint

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This is going to need a 0.5.1 release...

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I chose 1.3 due to the php 7 fixes.

**Comment by GrahamCampbell** [comment]
Great this is fixed now. :)

**Comment by bobthecow** [comment]
It works both ways, let's trust users to update to the latest one they can, rather than forcing a (potential) incompatibility with other libraries' dependencies.

**Comment by GrahamCampbell** [comment]
Sure. Glad this is fixed, whichever way. :)

**Comment by bobthecow** [comment]
(Sorry, was already in the middle of the hotfix when you opened this PR)

**Pull request closed without merging**
