### PR TITLE
clear code

### PR DESCRIPTION
**Pull request by ReenExe**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by ReenExe** [comment]
See this package in laravel and what delete some redundane `else`

**Comment by GrahamCampbell** [comment]
There's nothing wrong with them. The reverse refactor would also make a valid PR if you see what I mean.

**Comment by theofidry** [comment]
Well in the end it's just a matter of CS preferences. I do think the less indent you have, the more readable it tend to be, but I would also understand if not everyone shares this opinion.

**Comment by ReenExe** [comment]
Something wrong in this `checks` - i make changes in one files and StyleCI show other AutoCompleter.
So i retry, add link, and close this PR

**Comment by ReenExe** [comment]
Retry https://github.com/bobthecow/psysh/pull/303

**Pull request closed without merging**
