### PR TITLE
XDG Base Directory package change.

### PR DESCRIPTION
**Pull request by selcukcukur**
Reasons :

- Complies with PSR Coding Standards.
- PHP 5.6 , PHP 7.0 , PHP 7.1 , PHP 7.2, PHP 7.3 , PHP 7.4 , PHP 8.0 Supported.
- More readable code structure.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 This breaks installation on PHP 5.5.

**Comment by selcukcukur** [comment]
@GrahamCampbell It supports PHP 5.3 and higher with the last update just now.

**Comment by GrahamCampbell** [comment]
> PHP 5.6 , PHP 7.0 , PHP 7.1 , PHP 7.2, PHP 7.3 , PHP 7.4 , PHP 8.0 Supported.

Oh, I was mislead by this.

**Comment by GrahamCampbell** [comment]
TBH, I'd actually vote to take this in-house, rather than to switch to a package which does not have wide adoption and was only created yesterday.

**Comment by selcukcukur** [comment]
Hi, @GrahamCampbell 

- PHP Unit 9.x.x, 8.x.x, 7.x.x, 6.x.x, 5.x.x : https://github.com/CodeSax/BaseDirectory/releases/tag/v1.0.5
- PHP Unit 4.x.x, 5.x.x, 6.x.x 7.x.x, 8.x.x : https://github.com/CodeSax/BaseDirectory/releases/tag/v1.0.4

Code compatibility checks have been provided with PHPUnit for versions. The versions I mentioned above are compatible with the PHPUnit versions mentioned. You can choose the appropriate versions for "psysh" accordingly.

**Comment by bobthecow** [comment]
I'm with @GrahamCampbell. I've considered removing the external dependency entirely in the past, and if we make any change, it'd probably be to do just that. Though honestly, it's … kind of in house now? 🙂

Screenshot of the php-xdg-basedir packagist page, with @bobthecow listed as a maintainer

**Comment by selcukcukur** [comment]
Then the last two changes are like a better idea.  🙂

**Pull request closed without merging**
