### PR TITLE
Robust PHP 8.0 testing

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bobthecow** [comment]
This will probably error out :)

https://travis-ci.org/github/bobthecow/psysh/jobs/737910088

**Comment by bobthecow** [comment]
Oh just kidding! That failed because it didn't find the snapshot. Maybe this one will work.

**Comment by GrahamCampbell** [comment]
Gah, Travis is slow. Do you mind if I replace it with github actions in this PR?

**Comment by bobthecow** [comment]
Go for it! I've poked at it a bit but haven't gotten around to setting it up.

**Comment by GrahamCampbell** [comment]
I'll leave travis in place for your release process, but use actions for unit tests.

**Comment by GrahamCampbell** [comment]
That said, 5.5.9 prefer lowest is marked as allow fail? Is it even useful to test?

**Comment by GrahamCampbell** [comment]
TODO: actions code coverage

**Comment by GrahamCampbell** [comment]
Looks like the tests are failing due to PHPUnit too old: https://github.com/GrahamCampbell/psysh/runs/1317586158?check_suite_focus=true. I'll look into this tomorrow evening.

**Comment by bobthecow** [comment]
@GrahamCampbell where are we at with this one?

**Comment by GrahamCampbell** [comment]
I need to work out why I broke everything. :)

**Comment by bobthecow** [comment]
👋 any update on this?

**Comment by GrahamCampbell** [comment]
Sorry, I am not sure when I will have time to fix this. It no longer looks like a 5 minute job.

**Comment by bobthecow** [comment]
I've migrated releases to GitHub Actions now. I'll take a shot at doing it for testing as well.

**Comment by bobthecow** [comment]
Okay! We're now using GitHub actions for testing and release builds. I pulled in most of these changes, and made a few of my own, and everything is _passing_ on PHP < 8.0, and _running_ on 8.0.

I've temporarily marked 8.0 tests as YOLO to buy ourselves some time to work through the fixes. Backwards/forwards compatibility is getting a bit rough for PHPUnit, though it looks like they're going to add PHP 8.0 support to PHPUnit 8.5, so maybe holding off on PHPUnit 9.x until we no longer support PHP 5.x would be the way to go?

Side note: this is _stupid fast_ now. Should have made this change ages ago 😬

**Comment by GrahamCampbell** [comment]
:partyparrot:

**Pull request closed without merging**
