### PR TITLE
Bump travis

### PR DESCRIPTION
**Pull request by Taluu**
Removing unsupported versions from travis, and add newer versions.

We should really consider bumping php versions btw, as 5.6 is not even maintained anymore.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎

**Comment by Taluu** [comment]
Care to elaborate @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
See my other comment on your other PR.

**Comment by GrahamCampbell** [comment]
Also, this is already fixed on `develop`.

Please read https://github.com/bobthecow/psysh/blob/master/.github/CONTRIBUTING.md#branching-model.

**Comment by Taluu** [comment]
Yeah so I just added php 7.4 on the develop branch.

Maybe it's high time to make a release.

**Comment by bobthecow** [comment]
> Maybe it's high time to make a release.

Yeeeahhhh probably :)

**Pull request closed without merging**
