### PR TITLE
Tweaked a comment

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bobthecow** [comment]
@GrahamCampbell hates smiles :(

**Comment by Markcial** [comment]
yeah ¯\_(ツ)_/¯

**Comment by bobthecow** [comment]
Somewhat relevant: http://www.xkcd.com/541/

**Comment by Markcial** [comment]
xkcd, classy :D

**Comment by GrahamCampbell** [comment]
lol

**Comment by bobthecow** [comment]
Somewhat relevant:

emoticon-bugfix

**Comment by Markcial** [comment]
well played xD

**Comment by GrahamCampbell** [comment]
:)

**Pull request closed without merging**
