### PR TITLE
Formatter classes to … just functions?

### PR DESCRIPTION
**Pull request by bobthecow**
[Per a comment earlier today…](https://github.com/bobthecow/psysh/commit/6b3bfefe704397259702573d194a4eef1317934b#commitcomment-38417314)

> These would be functions if PHP supported function autoloading. I'm half tempted to make them functions anyway and just lean on Composer a bit more :)

Is this a terrible idea? It feels a lot cleaner to me.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The problem with functions like this is they don't play well with global installs of packages along slide local versions. For this reason, Guzzle is refactoring away from all functions to static class methods. https://github.com/guzzle/guzzle/pull/2546 https://github.com/guzzle/guzzle/issues/2511

**Comment by GrahamCampbell** [comment]
If someone has a different version of psysh installed globally to a local install, then composer will definitely load the wrong functions file for one of them...

**Comment by GrahamCampbell** [comment]
If those functions are different or don't exist in one file, then you run into issues, like in Guzzle.

**Comment by bobthecow** [comment]
Globally-installed psysh works around exactly these issues by always deferring to local.

**Comment by GrahamCampbell** [comment]
How does the local install stop composer from autoloading the global functions files first?

**Comment by GrahamCampbell** [comment]
I think that was the exact bug that guzzle was having?

**Comment by bobthecow** [comment]
The global `psysh` binary doesn't use the global composer installation at all if you have something installed locally. It loads the local one:

Screen Shot 2020-05-02 at 12 29 42 AM

Unless I'm misunderstanding the failure mode, you shouldn't ever hit any globally installed PsySH code if you're running a local installed version.

**Pull request closed without merging**
