### PR TITLE
Fixed CS Config

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There you go @bobthecow. Sorry I didn't get to this earlier. :)

**Comment by bobthecow** [comment]
Oh, nice. I didn't know about `long_array_syntax`.

I'll merge this for now, but I think the `method_argument_space` fixer is wrong. See [my comment on #222](https://github.com/bobthecow/psysh/issues/222#issuecomment-133878447) :)

**Comment by GrahamCampbell** [comment]
I think it's right. Maybe you need to make an issue for the PSR team to look at?

**Comment by GrahamCampbell** [comment]
Only they can collectively confirm what that rule actually meant, then we can take it from there. :)

**Comment by bobthecow** [comment]
It doesn't actually matter what they meant. Unless they update the spec (which they almost certainly won't) then it's ambiguous and both readings are valid.

**Comment by GrahamCampbell** [comment]
> Unless they update the spec (which they almost certainly won't) then it's ambiguous and both readings are valid.

I agree it's ambiguous, but I don't agree that the spec can't change. "Bug fixes" are surely a good thing, and the specs aren't never changed. As I said, it's not for me to say. You'd have to ask on the mailing list or something. :)

**Comment by bobthecow** [comment]
I didn't mean the spec can't change. I meant the spec almost certainly won't. I've been around the FIG long enough to realize that :P

**Comment by GrahamCampbell** [comment]
> I meant the spec almost certainly won't.

Lol, yeh, I know what you mean. It still might be worth getting some clarification though.

**Pull request merged**
