### PR TITLE
Support php-parser v3

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bobthecow** [comment]
Does PHP 7.1 not have an xdebug config to disable? can we make that line more robust, so it disables if it detects the config, rather than special casing versions we don't think will have it?

**Comment by bobthecow** [comment]
```
(php --ini | grep xdebug) && phpenv config-rm xdebug.ini
```

?

**Comment by GrahamCampbell** [comment]
NB Currently this code never actually resolves php parser 3.x since it's not stable.

**Comment by bobthecow** [comment]
oh, good to know. is 3.x required for 7.1?

**Comment by GrahamCampbell** [comment]
> oh, good to know. is 3.x required for 7.1?

Yeh, php parser 2.x doesn't parse php 7.1 code, though can parse older code on php 7.1 just fine.

**Comment by bobthecow** [comment]
🆒

**Comment by bobthecow** [comment]
oh, that xdebug thing prolly needs an `|| true` on the end to keep it from barfing when the result of grep is false.

**Comment by GrahamCampbell** [comment]
Ok, rebased this on develop.

**Comment by GrahamCampbell** [comment]
Ok, PHP-Parser made some breaking changes. Will investigate.

**Comment by GrahamCampbell** [comment]
@bobthecow Looks good now. This is needed in order to get Laravel properly onto PHP 7.1 since class preloader also depends on PHPParser.

**Comment by bobthecow** [comment]
Thanks! Any ideas why hhvm didn't finish? The xdebug change?

**Comment by bobthecow** [comment]
```
[[ "$TRAVIS_PHP_VERSION" != hhvm* ]] && (php --ini | grep xdebug) && phpenv config-rm xdebug.ini || true
```

… ought to do the trick?

**Comment by GrahamCampbell** [comment]
Passing now. :)

**Comment by bobthecow** [comment]
Awesome. Thank you.

**Pull request merged**
